-- ============================================
-- Specials Adelaide - New restaurants + specials batch
-- Sourced from eatdrinkcheap.com.au (May 2026)
-- Run this in Railway's Postgres query console
-- ============================================

-- New restaurants
INSERT INTO restaurants (id,name,suburb,cuisine,addr,lat,lng,active) VALUES ('r120','Storehouse Flinders East','Adelaide CBD','Bar','260 Flinders St',-34.9239,138.6079,true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr,lat=EXCLUDED.lat,lng=EXCLUDED.lng;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,lat,lng,active) VALUES ('r121','The Guardsman','Adelaide CBD','Casino Bar','SkyCity, 125 North Tce',-34.9211,138.5942,true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr,lat=EXCLUDED.lat,lng=EXCLUDED.lng;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,lat,lng,active) VALUES ('r122','SOL Rooftop','Adelaide CBD','Rooftop Bar','SkyCity, 125 North Tce',-34.9211,138.5942,true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr,lat=EXCLUDED.lat,lng=EXCLUDED.lng;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,lat,lng,active) VALUES ('r123','Park Hotel','Adelaide CBD','Pub','19 King William St',-34.9211,138.5992,true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr,lat=EXCLUDED.lat,lng=EXCLUDED.lng;

-- New specials sourced from eatdrinkcheap.com.au (May 2026)
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx1','r12','Coopers Alehouse Happy Hour','$8.50 selected Coopers pints, $7 house wines, $8.50 base spirits or $12 Aperol Spritz',8.5,'drinks','drinks','{"monday","tuesday","wednesday","thursday","friday","saturday","sunday"}','4pm','5pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx2','r83','Sunday Bottomless Tasting Menu','4-course tasting menu with live sax & DJ from 2-4pm. 10% Sunday surcharge applies, bookings essential',89,'brunch','brunch','{"sunday"}','12pm','3pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx3','r70','Wednesday Schnitzel Special','Full-size schnitzel with salad and veg bar, warm bread rolls, roast veg, potato bake and assorted salads. Choice of chicken, beef or eggplant',20,'schnitzel','dinner','{"wednesday"}','12pm','9pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx4','r123','Schnitzel Night','Choice of beef, chicken, squid or vegan schnitzel. Dine in or takeaway, bookings available online',20,'schnitzel','dinner','{"thursday"}','5:30pm','9pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx5','r120','Storehouse Happy Hour','Local wines $8, any bottled beer $8, or signature cocktails $15',8,'drinks','drinks','{"monday","tuesday","wednesday","thursday","friday","saturday"}','4pm','6pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx6','r121','Casino Happy Hour','Selected beer, house wine and house spirits $6',6,'drinks','drinks','{"monday","tuesday","wednesday","thursday","friday"}','4pm','7pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx7','r21','Tuesday Schnitzel & Wings','Chicken or Beef Schnitzel with chips and salad $21. Toppers extra: Parmigiana +$6, Mexican +$6, Aussie +$6, Hawaiian +$5. Not valid public holidays',21,'schnitzel','dinner','{"tuesday"}','12pm','9pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx8','r21','Tuesday Wings & Trivia','1kg of wings $20, then free quiz night by QuizzaMe from 7pm',20,'wings','dinner','{"tuesday"}','5pm','9pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx9','r93','All-Day Drinks Deal','$8.90 Coors Pints, $11.90 Margaritas and Long Island Iced Teas - no need to wait for happy hour',8.9,'drinks','drinks','{"monday","tuesday","wednesday","thursday"}','12pm','9pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx10','r29','2-for-1 Schnitzel Wednesday','Bring a friend and enjoy 2-for-1 schnitzels. T&Cs apply, not valid with other offers',20,'schnitzel','dinner','{"wednesday"}','5pm','9pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx11','r31','Brewhouse Happy Hour','$7 house wine, pints of tap beer and base spirits - every single day',7,'drinks','drinks','{"monday","tuesday","wednesday","thursday","friday","saturday","sunday"}','4pm','6pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx12','r27','Rooftop Happy Hour','Spirits from $10, beer from $12 and spritz $15 with stunning views over Victoria Square',10,'drinks','drinks','{"thursday","friday","saturday"}','4pm','6pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx13','r26','Wednesday Rump Steak','Juicy 250g rump steak with hot chips, fresh house salad and your choice of sauce',26,'steak','dinner','{"wednesday"}','12pm','9pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx14','r30','Steak, Chips & Salad Deal','All-day special - steak, chips and salad $20 with the purchase of any drink',20,'steak','dinner','{"wednesday"}','12pm','9pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx15','r23','Friday Happy Hour','$7 pints, base spirits and house wines - grab your mates for that well-deserved after-work drink',7,'drinks','drinks','{"monday","tuesday","wednesday","thursday","friday"}','4pm','6pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx16','r28','Sports Bar Happy Hour','Sports bar $7.50 pints & $7 house wine. Club lounge $8 pints & $7 house wine',7.5,'drinks','drinks','{"monday","tuesday","wednesday","thursday","friday"}','4pm','6pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx17','r54','Espresso Martini Happy Hour','Popular espresso martini happy hour - Friday and Saturday',14,'drinks','drinks','{"friday","saturday"}','7pm','8pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx18','r76','2 Cocktails for $25','Order straight from your table via Mr Yum - two delicious cocktails for $25',25,'drinks','drinks','{"friday","saturday"}','8pm','9pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx19','r79','Weekday Lunch Special','Lunch specials with meals starting from $17.90',17.9,'roast','lunch','{"monday","tuesday","wednesday","thursday","friday"}','11am','3pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx20','r68','Burger or Schnitzel & Pint','Any burger or schnitzel with a pint of Coopers $22',22,'burger','dinner','{"friday","saturday"}','12pm','8pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
INSERT INTO specials (id,rid,name,desc_text,price,food,session,days,from_time,until_time,active) VALUES ('sx21','r122','Saturday Bottomless Brunch','Bottomless brunch at SOL Rooftop with sweeping city views - bookings essential',79,'brunch','brunch','{"saturday"}','11am','2pm',true) ON CONFLICT (id) DO UPDATE SET rid=EXCLUDED.rid,name=EXCLUDED.name,desc_text=EXCLUDED.desc_text,price=EXCLUDED.price,food=EXCLUDED.food,session=EXCLUDED.session,days=EXCLUDED.days,from_time=EXCLUDED.from_time,until_time=EXCLUDED.until_time,active=EXCLUDED.active;
