-- ════════════════════════════════════════════
-- Specials Adelaide — Seed Restaurants (53 venues)
-- Run AFTER schema.sql
-- Specials table is left EMPTY for manual entry via admin
-- ════════════════════════════════════════════

INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r1','Cumberland Arms Hotel','Adelaide CBD','Australian','205 Waymouth St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r2','General Havelock Hotel','Adelaide CBD','Australian','162 Hutt St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r3','Union Hotel','Adelaide CBD','Australian','70 Waymouth St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r4','Gilbert Street Hotel','Adelaide CBD','Australian','88 Gilbert St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r5','The Laneway Social','Adelaide CBD','Bar','29 Ebenezer Place',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r6','Benjamin On Franklin','Adelaide CBD','Bar','148 Franklin St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r7','Lady Burra Brewhouse','Adelaide CBD','Brewery','3 Nile St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r8','Duke of Brunswick Hotel','Adelaide CBD','Australian','207 Gilbert St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r9','Duke of York Hotel','Adelaide CBD','Australian','81-83 Grenfell St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r10','Rob Roy Hotel','Adelaide CBD','Australian','Corner Grenfell & Pulteney St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r11','The Austral','Adelaide CBD','Australian','205 Rundle St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r12','Coopers Alehouse','Adelaide CBD','Australian','226 Rundle St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r13','PJ O''Briens','Adelaide CBD','Irish','Grenfell St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r14','Norwood Hotel','Norwood','Australian','97 The Parade',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r15','Alma Tavern','Norwood','Australian','66 Magill Rd',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r16','The Kensi','Marryatville','Australian','23 Regent St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r17','Feathers Hotel','Burnside','Australian','Greenhill Rd',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r18','Parkside Hotel','Parkside','Australian','142 Glen Osmond Rd',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r19','Sportys','Fullarton','Australian','150 Glen Osmond Rd',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r20','Tower Hotel','Magill','Australian','621 Magill Rd',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r21','Hampstead Hotel','Clearview','Australian','184 Hampstead Rd',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r22','Enfield Hotel','Clearview','Australian','184 Hampstead Rd',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r23','Northern Tavern','Sefton Park','Australian','269 Main N Rd',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r24','Windmill Hotel','Prospect','Australian','94 Main N Rd',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r25','Hecho En Mexico','Prospect','Mexican','Prospect Rd',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r26','Cathedral Hotel','North Adelaide','Australian','45 Kermode St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r27','Lord Melbourne Hotel','North Adelaide','Australian','63 Melbourne St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r28','Grand Junction Tavern','Pennington','Australian','174 Grand Junction Rd',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r29','Excelsior Hotel','Brompton','Australian','110 Coglin St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r30','Lockleys Hotel','Fulham','Australian','493 Henley Beach Rd',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r31','Mile End Hotel','Mile End','Australian','30 Henley Beach Rd',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r32','Ambra Spirits','Thebarton','Italian','',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r33','Bartley Hotel','West Lakes Shore','Australian','Bartley Terrace',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r34','Seaton Hotel','Seaton','Australian','253 Tapleys Hill Rd',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r35','Cremorne Hotel','Unley','Australian','207 Unley Rd',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r36','Belair Hotel','Mitcham','Australian','',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r37','Gully Public House','Adelaide Hills','Australian','',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r38','Aldgate Pump Hotel','Adelaide Hills','Australian','Aldgate',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r39','Marion Hotel','Mitchell Park','Australian','849 Marion Rd',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r40','Emu Hotel','Morphett Vale','Australian','132 Main South Rd',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r41','TGI Fridays','Oaklands Park','American','293 Diagonal Rd',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r42','Seamore''s','Henley Beach','Italian','255 Esplanade',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r43','Henley Beach Hotel','Henley Beach','Australian','157 Esplanade',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r44','Largs Pier Hotel','Largs Bay','Australian','Esplanade',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r45','Beach Hotel Seaford','Seaford','Australian','Griffiths Drive',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r46','Beach Burrito Co','Glenelg','Mexican','56 Jetty Rd',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r47','Mismatch Brewing Co','Adelaide CBD','Brewery','55 Nile St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r48','Bandit Pizza','Adelaide CBD','Italian','',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r49','Good Gilbert','Adelaide CBD','Modern Australian','Gilbert St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r50','Fleet Street Social','Adelaide CBD','Bar','Fleet St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r51','Grunthal Brewhouse','Adelaide Hills','Brewery','',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r52','Bar Lune','Adelaide CBD','Wine Bar','',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r53','Gilbert Street Hotel','Adelaide CBD','Australian','88 Gilbert St',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
INSERT INTO restaurants (id,name,suburb,cuisine,addr,active) VALUES ('r54','La Scala Cafe','Adelaide CBD','Italian','',true) ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,suburb=EXCLUDED.suburb,cuisine=EXCLUDED.cuisine,addr=EXCLUDED.addr;
